version: '3.8'

services:
  db:
    image: postgres:14-alpine
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PORT=${DB_PORT}
    restart: "on-failure"


volumes:
  postgres_data: